
#include "lib/basic.h"
#include "lib/alloc.h"
#include "lib/log.h"
#include "lib/string.h"
#include "lib/vec.h"
#include "lib/reflect.h"
#include "engine.h"
#include "platform.h"
#include "gui.h"
#include "lib/alloc.cpp"
#include "lib/string.cpp"
#include "engine.cpp"
#include "platform.cpp"
#include "gui.cpp"
