
#include <typeinfo>
#include "engine/basic.h"
#include "engine/math.h"
#include "engine/ds/string.h"
#include "engine/util/context.h"
#include "engine/platform/platform_api.h"
#include "engine/util/fptr.h"
#include "engine/ds/alloc.h"
#include "engine/ds/vector.h"
#include "engine/ds/stack.h"
#include "engine/ds/array.h"
#include "engine/ds/queue.h"
#include "engine/ds/map.h"
#include "engine/ds/buffer.h"
#include "engine/ds/heap.h"
#include "engine/util/reflect.h"
#include "engine/log_html.h"
#include "engine/log.h"
#include "engine/threads.h"
#include "engine/asset.h"
#include "engine/render.h"
#include "engine/events.h"
#include <imgui/imgui.h>
#include "engine/imgui.h"
#include "engine/dbg.h"
#include "engine/util/threadstate.h"
#include "engine/engine.h"
#include "game/gfx.h"
#include "game/world.h"
#include "game/console.h"
#include "game/exile.h"

#ifndef __clang__
// #include "engine/util/fptr.cpp"
// #include "engine/util/context.cpp"
// #include "engine/util/threadstate.cpp"
// #include "engine/util/reflect.cpp"
// #include "engine/log.cpp"
// #include "engine/events.cpp"
// #include "engine/render.cpp"
// #include "engine/dbg.cpp"
// #include "engine/asset.cpp"
// #include "engine/threads.cpp"
// #include "engine/engine.cpp"
// #include "engine/imgui.cpp"
// #include "engine/ds/alloc.cpp"
// #include "engine/ds/string.cpp"
// #include "engine/ds/string.inl"
// #include "engine/ds/vector.inl"
// #include "engine/ds/stack.inl"
// #include "engine/ds/array.inl"
// #include "engine/ds/queue.inl"
#include "engine/ds/map.inl"
// #include "engine/ds/buffer.cpp"
// #include "engine/ds/heap.cpp"
// #include "game/console.cpp"
// #include "game/gfx.cpp"
// #include "game/world.cpp"
// #include "game/exile.cpp"
#endif
